# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='company name'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='PAN number'),
        ),
    ]
